POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 2",
    "description": "Category 2 description"
}

###

GET http://localhost:8080/category/87057405-5b60-4136-afb2-2928c29073b6 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 2",
    "description": "Product 2 description",
    "price": 100,
    "image_url": "http://www.google.com",
    "category_id": "87057405-5b60-4136-afb2-2928c29073b6"
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/2ddd4761-287c-4d49-b521-748ade9e8fdd HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### 

GET http://localhost:8080/product/category/87057405-5b60-4136-afb2-2928c29073b6 HTTP/1.1
Host: localhost:8080
Content-Type: application/json